# Generated by Django 3.2.5 on 2021-07-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_created=True, verbose_name='Время создания кода')),
                ('link', models.URLField(verbose_name='Ссылка для QR-кода')),
                ('qr', models.ImageField(upload_to='static/qrs', verbose_name='Сгенерированный код')),
            ],
            options={
                'verbose_name': 'QR-код',
                'verbose_name_plural': 'QR-коды',
            },
        ),
    ]
