# Generated by Django 3.2.5 on 2021-07-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_qr_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время создания кода'),
        ),
    ]
