# Generated by Django 3.2.5 on 2021-07-08 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_qr_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 7, 8, 12, 11, 9, 16641, tzinfo=utc), verbose_name='Время создания кода'),
        ),
    ]
