# Generated by Django 3.2.5 on 2021-07-08 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_qr_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='qr',
        ),
        migrations.AddField(
            model_name='qr',
            name='qr_1',
            field=models.ImageField(default=1, upload_to='static/qrs', verbose_name='Сгенерированный код 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qr',
            name='qr_2',
            field=models.ImageField(default=1, upload_to='static/qrs', verbose_name='Сгенерированный код 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qr',
            name='qr_3',
            field=models.ImageField(default=1, upload_to='static/qrs', verbose_name='Сгенерированный код 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qr',
            name='qr_4',
            field=models.ImageField(default=1, upload_to='static/qrs', verbose_name='Сгенерированный код 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qr',
            name='qr_5',
            field=models.ImageField(default=1, upload_to='static/qrs', verbose_name='Сгенерированный код 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qr',
            name='qr_6',
            field=models.ImageField(default=1, upload_to='static/qrs', verbose_name='Сгенерированный код 6'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qr',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 7, 8, 15, 5, 30, 569851, tzinfo=utc), verbose_name='Время создания кода'),
        ),
    ]
